### ISSUE TITLE
Install instructions request

### ISSUE THREAD

**Issue by jackdpeterson** [davidglevy/eclipse-icon-enlarger#1]
Hey, I'm looking to implement this in my instance of eclipse (actually Zend Studio 10.6). Would you be willing to add in the necessary steps to get this working from the ground up in the readme.md?

Thanks

**Comment by vadimpanin** [comment]
You would basically need to download the recent version of Eclipse for Java (you can set it up separately from Zend Studio), then using Marketplace download Spring Tools Suite. Then clone the project and File->Import it as Maven project. Most likely you will encounter pom error like "Plugin execution not covered by lifecycle configuration", in that case you will need to install "Maven Integration for Eclipse"  (m2e). When the build is complete, create new Run Configuration from Run menu, set Main Class to testEclipse.FixIcons and Arguments to "-b c:\eclipse_src -o c:\eclipse_dst". You would want to backup/copy your existing installation, just in case. Then click run.

**Comment by jackdpeterson** [comment]
Thanks, looks like that was successful (now running and chewing through some CPU)!
