### ISSUE TITLE
Merging PhantomYdn with master?

### ISSUE THREAD

**Issue by cmaggiulli** [davidglevy/eclipse-icon-enlarger#10]
I spent several unnecessary hours building the same functions into this repo that were already present in PhantomYdn's fork.  Can we merge that, I will add a review? I forked PhantomYdn's fork and am adding a few other additional functions tonight including output directory creation, verifying (by file count) if the output directory contains all files as input directory.  What do we think about comparing output directory file count with input directory file count, and if the counts are the same, we make a backup copy of the -b, zip it to a temp location, replace the old -b with -o, then add -b backup to -o root directory?

**Comment by davidglevy** [comment]
Hey sorry have really been too busy to "own" this project - let me know if you're interested and I'll make you a collaborator.

**Comment by cmaggiulli** [comment]
Hey Haven't logged in for some time  if that original post sounded a bit forward I apologize. our department upgraded hardware and this stopped our sprint. Have you tried attempted to use external manifest files?  I have been successful using that method and it has been satisfactory.  Have mostly abandoned this issue unless there is a specific use case in which external manifest doesn't work

**Comment by cmaggiulli** [comment]
I'd be interested in being added as collaborator nonetheless as i did implement some features. I'm sure it's sitting in a workspace somewhere
